### PR TITLE
add loop options

### PR DESCRIPTION
**Pull request by TehPig**

### CODE REVIEW

**Comment by ThePedroo** [comment]
Thanks for this PR, but for making a track/queue loop we would also need to save the pos of the current playing song
Well, if you want, I can do that for you, but if you want to contribute, feel free to do it and ask any questions for me

**Comment by TehPig** [comment]
Ah, I forgot to add the other file to the pull request, I am new to this.

**Comment by TehPig** [comment]
And I also have to define some variables in order for this to function.

**Comment by ThePedroo** [comment]
Oh, no problem, please use git commit --amend and git push --force-with-lease to not create a lot of commits :)

**Comment by TehPig** [comment]
I am doing everything through github.

**Comment by ThePedroo** [comment]
Oh, I'll merge the commits in one in the end anyways, soo, feel free

**Review by ThePedroo — CHANGES_REQUESTED** [review]
Do you think would be necessary to add those changes? In case the user doesn't provide a type
If you think it is, will also need to change the other PR.

```
+ /**
+  * Sets the loop type of the player's queue.
+  * @returns {undefined} Won't return nothing.
+  */
  setLoop(type) {
    let players = map.get('players') || {}
    
    switch (type) {
      case 'track':
        players[this.config.guildId] = { ...players[this.config.guildId], loop: 'track' }
        break;
      case 'queue':
        players[this.config.guildId] = { ...players[this.config.guildId], loop: 'queue' }
        break;
      case 'off':
+    default:
-        players[this.config.guildId] = { ...players[this.config.guildId], loop: 'off' }
+       players[this.config.guildId] = { ...players[this.config.guildId], loop: null' }
        break;
    }
  }
  ```

**Comment by TehPig** [comment]
In that code, case 'off' has no code to run

**Comment by ThePedroo** [comment]
Oh, it has, if you group for example, a amount of cases, they will all execute the same code, for example:

```case 'abc':
case 'abc2':
case '123:
  console.log('one of those')

  break;
```

they will all execute the same console.log if it's abc, abc2 or 123

**Pull request merged**
