### PR TITLE
update file to accept looping options

### PR DESCRIPTION
**Pull request by TehPig**

### CODE REVIEW

**Review by ThePedroo — COMMENTED** [review]
Same here, could you change it to switch?

**Comment by TehPig** [comment]
I'll do it soon, coding on phone is tough.

**Review by ThePedroo — CHANGES_REQUESTED** [review]
You mistyped, you are using case with a ; in the end, could you just fix that? Just that and I'll merge

**Comment by TehPig** [comment]
Done, I typed the code on my phone and did not notice the typos

**Review by ThePedroo — COMMENTED** [review]
Sorry for being annoying, but could you please remove the ; frm the functions like:
```
queue[data.guildId].shift();
```
to
```
queue[data.guildId].shift()
```

**Comment by TehPig** [comment]
it's the same thing

**Comment by ThePedroo** [comment]
I know, but to keep the standard indentation, would be better removing the ; in the end of the functions

**Pull request merged**
